### ISSUE TITLE
drill without outline causes segfault 

### ISSUE THREAD

**Issue by mgmax** [patkan/pcb2gcode#2]
If I don't specify an outline gerber file, but only drilling data, the program segfaults.

Running inside gdb:

	pcb2gcode --metric --metricoutput --zsafe 10 --zchange 100 --zdrill 3 --drill-feed 200 --drill-speed 18000 --zcut 3 --cutter-diameter 3 --cut-feed 100 --cut-infeed 50 --cut-speed 18000 --g64 0.05 --drill anschlussplatine.drl
	[Thread debugging using libthread_db enabled]
	Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
	Warning: Board dimensions unknown. Gcode for drilling probably misaligned on Y-axis.
	Importing front side... not specified.
	Importing back side... not specified.
	Importing outline... not specified.
	Internal Error: No layers prepared.

	Program received signal SIGSEGV, Segmentation fault.
	operator-> (this=<optimized out>) at board.cpp:198
	198     }
	(gdb) bt
	#0  operator-> (this=<optimized out>) at board.cpp:198
	#1  Board::get_width (this=0x65d430) at board.cpp:51
	#2  0x000000000040d569 in main (argc=<optimized out>, argv=<optimized out>) at main.cpp:318

**Comment by patkan** [comment]
This seems to be solved in "upstream" (pcb2gcode/pcb2gcode). Correct?

**Comment by Corna** [comment]
It is still broken for me... Are you sure?

**Comment by Corna** [comment]
It is now fixed in commit pcb2gcode/pcb2gcode@6d9a8d1ffbb885ae42d61d1d351a7657ddab1c7f

**Comment by patkan** [comment]
OK, thanks. This seems to be fixed now, you were right. Before it wasn't working (sloppy testing). (Atm it throws another segfault, but I have to examine this in detail. Might be something else. I will open an issue if needed.)
